### ISSUE TITLE
Set as default is not usable

### ISSUE THREAD

**Issue by thebaz** [RaceX58/RaceX.Dashboard.Manager#5] opened 2022-02-08 08:53 UTC
I have a USBD480 on my GSI wheel... I can't use the "Set as default dashboard for the game" button (can't select)

**Comment by GRPDAN01** [comment] 2022-02-11 08:28
I can't reproduce this issue. Could you please post a screen capture?

**Comment by RaceX58** [comment] 2022-02-11 08:29
I can't reproduce this issue. Could you please add a screen capture?

**Comment by thebaz** [comment] 2022-03-18 14:54
![Immagine 2022-03-18 155420](https://user-images.githubusercontent.com/7090323/159026391-5dc7b367-4d87-4512-9569-3dd196769bc6.png)

**Comment by RaceX58** [comment] 2022-04-19 14:32
Resolved in #7

**Closed as completed by RaceX58** 2022-04-19 14:32 UTC

**Comment by thebaz** [comment] 2022-04-19 14:48
Thanks, works as expected
